title: Sero Wiki
description: A framework for Seroanalytics using multiplex serology
theme: just-the-docs

url: https://mikamalouf.github.io/sero_wiki/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
